0.5.0     - 'check_status_re' and therefore 'runpipe_re' use 'grep -E'       instead of 'grep' in order to simplify regexp that       contains >=2 digit exit statuses.
      NOTE: Formally speaking this breaks backward compatibility.

    - If PIPESTATUS_VERBOSE variable is set to non-empty string, then
      check_status0 and check_status_re functions print an error
      message to stderr.

diff --git a/pipestatus b/pipestatus
--- a/pipestatus
+++ b/pipestatus
@@ -12,6 +12,13 @@
 # Version 0.4.0
 #
 
+# 
+__pipestatus_err_msg (){
+    if test "$PIPESTATUS_VERBOSE"; then
+	echo "Pipe failed, pipestatus_all='$pipestatus_all'" 1>&2
+    fi
+}
+
 # run pipe and set pipestatus_1, pipestatus_2, ... and pipesize variables
 # Example: runpipe_base prog1 arg11 arg12 '|' prog2 arg21 arg22 '|' prog3
 # Always return zero exit status
@@ -86,7 +93,10 @@ runpipe_base (){
 check_status0 (){
     __pipestatus_j=1
     while [ "$__pipestatus_j" -le "$pipesize" ]; do
-	eval "[ \$pipestatus_$__pipestatus_j -eq 0 ]" || return 1
+	eval "[ \$pipestatus_$__pipestatus_j -eq 0 ]" || {
+	    __pipestatus_err_msg
+	    return 1
+	}
 	__pipestatus_j=$(($__pipestatus_j+1))
     done
 
@@ -112,10 +122,12 @@ check_status_re (){
     done
 
     # trick for set -e
-    if echo "$__pipestatus_ps" | grep "^ $__pipestatus_re"'$' > /dev/null; then
-	__pipestatus_ret=$?
+    if echo "$__pipestatus_ps" | grep -E "^ $__pipestatus_re"'$' > /dev/null
+    then
+	__pipestatus_ret=0
     else
 	__pipestatus_ret=$?
+	__pipestatus_err_msg
     fi
 
     # egrep not found?
